name: nginx-proxy

on:
  push:
    tags:
      - nginx-proxy/*-alpine
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: true
        type: string
        default: "nginx-proxy/1.27.3-alpine"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Variables
        id: myval
        run: |
          bash build.sh

      - name: Change Dockerfile
        run: |
          sed -i "s/FROM nginx.*alpine/FROM nginx:${{ steps.myval.outputs.build_version }}/" ./nginx-proxy/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.myval.outputs.build_name }}
          build-args: |
            VERSION=${{ steps.myval.outputs.build_version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.myval.outputs.tag_version }}
            ${{ steps.myval.outputs.tag_latest }}

      - name: Delete Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 3
