name: sing-box

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The tag(version) you want to build"
        required: true
        type: string
        default: "v1.13.2"
      project_name:
        description: "The project name you want to build"
        required: true
        default: 'sing-box'
        type: choice
        options:
          - sing-box
          - nginx-proxy
          - nginx-http

env:
  PROJECT_NAME: ${{ github.event.inputs.project_name }}
  TAG_NAME: ${{ github.event.inputs.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone Repo
        working-directory: ${{ env.PROJECT_NAME }}
        run: |
          git clone --depth=1 -b ${{ env.TAG_NAME}} https://github.com/SagerNet/sing-box.git src
          echo "tag_name: ${{ env.TAG_NAME }}"
          echo "app_name: ${{ env.PROJECT_NAME }}"

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v4
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v4
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and Push
      #   uses: docker/build-push-action@v7
      #   with:
      #     context: ./${{ env.PROJECT_NAME }}
      #     build-args: |
      #       VERSION=${{ env.TAG_NAME }}
      #       SRC_DIR=src
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ env.TAG_NAME }}
      #       ${{ secrets.DOCKERHUB_REGISTRY }}/${{ env.PROJECT_NAME }}:latest

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          RELEASE_TAG: ${{ env.PROJECT_NAME }}/${{ env.TAG_NAME}}
          RELEASE_TITLE: ${{ env.PROJECT_NAME }}/${{ env.TAG_NAME}}
          RELEASE_NOTES: "Build from ${{ env.PROJECT_NAME }} ${{ env.TAG_NAME }}"
        run: |
          echo "--- 正在处理 Release $RELEASE_TAG ---"    
          # 检查 Release 是否已经存在
          if gh release view "$RELEASE_TAG" >/dev/null 2>&1; then
            echo "Release 已存在，跳过..."
          else
            echo "创建新 Release..."
            gh release create "$RELEASE_TAG" \
              --title "$RELEASE_TITLE" \
              --notes "$RELEASE_NOTES"
          fi