name: sing-box

on:
  push:
    tags:
      - sing-box/v*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: true
        type: string
        default: "sing-box/v1.7.8"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get my variable
        id: myval
        run: |
          if [ "${{ github.event.inputs.tag }}" ]; then
            tmp_tag="${{ github.event.inputs.tag }}"
          else
            tmp_tag="${{ github.ref_name }}"
          fi
          tmp_name=$(echo ${tmp_tag} | awk -F '/' '{print $1}')
          tmp_version=$(echo ${tmp_tag} | awk -F '/' '{print $2}')
          echo "tag_latest=${{ secrets.DOCKERHUB_REGISTRY }}/${tmp_name}:latest" >> $GITHUB_OUTPUT
          echo "tag_version=${{ secrets.DOCKERHUB_REGISTRY }}/${tmp_name}:${tmp_version}" >> $GITHUB_OUTPUT
          echo "build_name=${tmp_name}" >> $GITHUB_OUTPUT
          echo "build_version=${tmp_version}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ steps.myval.outputs.build_name }}
          build-args: |
            VERSION=${{ steps.myval.outputs.build_version }}
          push: true
          tags: |
            ${{ steps.myval.outputs.tag_version }}
            ${{ steps.myval.outputs.tag_latest }}