name: sing-box

on:
  push:
    tags:
      - sing-box/v*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: true
        type: string
        default: "sing-box/v1.10.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Variables
        id: myval
        run: ./build.sh

      - name: Clone Repo
        working-directory: ${{ steps.myval.outputs.build_name }}
        run: |
          git clone --depth=1 -b ${{ steps.myval.outputs.build_version }} https://github.com/SagerNet/sing-box.git ${{ steps.myval.outputs.build_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.myval.outputs.build_name }}
          build-args: |
            VERSION=${{ steps.myval.outputs.build_version }}
            SRC_DIR=${{ steps.myval.outputs.build_name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.myval.outputs.tag_version }}
            ${{ steps.myval.outputs.tag_latest }}

      - name: Delete Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 3
