name: sing-box-auto

on:
  schedule:
    - cron: "20 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Variables
        id: myval
        run: |
          sudo -E curl -fsSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo -E chmod +x /usr/local/bin/yq
          bash sing-box/auto.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: steps.myval.outputs.release_status == 'yes'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: "${{ steps.myval.outputs.release_tag }}"
          body: "${{ steps.myval.outputs.release_tag }}"

      - name: Delete Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 3

      - name: Delete Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true
